output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value       = module.eks.kubectl_config
}

output "node_group_asg_name" {
  description = "Name of the Auto Scaling Group for the node group"
  value       = module.eks.eks_managed_node_groups["eks_nodes"].node_group_autoscaling_group_names[0]
}
