---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shubhamchau/td-backend:v1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: CLOUD_NAME
              value: dummy
            - name: API_KEY
              value: "dummy"
            - name: API_SECRET
              value: dummy
            - name: SECRET
              value: abc
            - name: DB
              value: mongodb://database:27017/techdome
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

